name: Update Pluto Playlist & EPG Data

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
    
    - name: Run Pluto Data Script
      run: php php/get_pluto.php
      continue-on-error: true

    - name: List Files in pluto Directory
      run: ls -l pluto

    - name: Add generated files to Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add pluto/us.m3u8 pluto/us.xml
        git commit -m "Update Pluto TV EPG and playlist"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
